// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gfonts} from '../models';
import {installer} from '../models';

export function GetCategories():Promise<Array<string>>;

export function GetFamily(arg1:string):Promise<gfonts.FontFamily>;

export function GetSubsets():Promise<Array<string>>;

export function Install(arg1:installer.InstallRequest):Promise<installer.InstallResult>;

export function ListFonts(arg1:gfonts.ListQuery):Promise<gfonts.ListResult>;

export function NeedsAPIKey():Promise<boolean>;

export function OpenURL(arg1:string):Promise<void>;

export function RefreshCatalog():Promise<void>;

export function ScanInstalled(arg1:Array<string>):Promise<Record<string, Array<string>>>;

export function SetAPIKey(arg1:string):Promise<void>;

export function StartupError():Promise<string>;
