// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCategories() {
  return window['go']['main']['App']['GetCategories']();
}

export function GetFamily(arg1) {
  return window['go']['main']['App']['GetFamily'](arg1);
}

export function GetSubsets() {
  return window['go']['main']['App']['GetSubsets']();
}

export function Install(arg1) {
  return window['go']['main']['App']['Install'](arg1);
}

export function ListFonts(arg1) {
  return window['go']['main']['App']['ListFonts'](arg1);
}

export function NeedsAPIKey() {
  return window['go']['main']['App']['NeedsAPIKey']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function RefreshCatalog() {
  return window['go']['main']['App']['RefreshCatalog']();
}

export function ScanInstalled(arg1) {
  return window['go']['main']['App']['ScanInstalled'](arg1);
}

export function SetAPIKey(arg1) {
  return window['go']['main']['App']['SetAPIKey'](arg1);
}

export function StartupError() {
  return window['go']['main']['App']['StartupError']();
}
